[package]
name = "driver-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
sysinfo = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1.41"
anyhow = "1"
libloading = "0.8"
cluaiz-shared = { package = "bitshit-shared", path = "../Inference-engine/engines/cluaiz-shared" }
